training: !Training
  destination: aws
  instance_type: ml.p3.2xlarge
  instance_count: 1
  training_input_path: s3://jumpstart-cache-prod-us-east-1/training-datasets/tc/data.csv
  hyperparameters: !Hyperparameters
    epochs: 1
    per_device_train_batch_size: 32
    learning_rate: 0.01

models:
- !Model
  id: tensorflow-tc-bert-en-uncased-L-12-H-768-A-12-2
  version: 1.0.0
  source: sagemaker