deployment: !Deployment
  destination: aws
  endpoint_name: huggingface-tc-bert-base-cased-202403291810
  instance_count: 1
  instance_type: ml.m5.xlarge
  num_gpus: 1
  quantization: null
models:
- !Model
  location: null
  predict: null
  id: huggingface-tc-bert-base-cased
  version: 2.*
  source: sagemaker
  task: tc
